// <auto-generated />
using System;
using EnergyCom.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnergyCom.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EnergyCom.Domains.CalculoDados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("ConsumoForaKwh")
                        .HasColumnType("double");

                    b.Property<double>("ConsumoPontaKwh")
                        .HasColumnType("double");

                    b.Property<double>("ConsumoTotalKwh")
                        .HasColumnType("double");

                    b.Property<int>("Iduc")
                        .HasColumnType("int");

                    b.Property<double>("LeituraAnterior")
                        .HasColumnType("double");

                    b.Property<double>("LeituraAtual")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("Iduc");

                    b.ToTable("CalculoDados");
                });

            modelBuilder.Entity("EnergyCom.Domains.Consumidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DebitoConta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Inscricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Consumidor");
                });

            modelBuilder.Entity("EnergyCom.Domains.Fatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCalculo")
                        .HasColumnType("int");

                    b.Property<int>("Iduc")
                        .HasColumnType("int");

                    b.Property<int>("MotivoBaixa")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("IdCalculo");

                    b.HasIndex("Iduc");

                    b.ToTable("Fatura");
                });

            modelBuilder.Entity("EnergyCom.Domains.Uc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Classe")
                        .HasColumnType("int");

                    b.Property<int>("Grupo")
                        .HasColumnType("int");

                    b.Property<int>("IdConsumidor")
                        .HasColumnType("int");

                    b.Property<int>("SubClasse")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdConsumidor");

                    b.ToTable("Uc");
                });

            modelBuilder.Entity("EnergyCom.Domains.CalculoDados", b =>
                {
                    b.HasOne("EnergyCom.Domains.Uc", "Uc")
                        .WithMany("CalculoDados")
                        .HasForeignKey("Iduc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uc");
                });

            modelBuilder.Entity("EnergyCom.Domains.Fatura", b =>
                {
                    b.HasOne("EnergyCom.Domains.CalculoDados", "CalculoDados")
                        .WithMany("Faturas")
                        .HasForeignKey("IdCalculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnergyCom.Domains.Uc", "Uc")
                        .WithMany("Faturas")
                        .HasForeignKey("Iduc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalculoDados");

                    b.Navigation("Uc");
                });

            modelBuilder.Entity("EnergyCom.Domains.Uc", b =>
                {
                    b.HasOne("EnergyCom.Domains.Consumidor", "Consumidor")
                        .WithMany("Ucs")
                        .HasForeignKey("IdConsumidor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumidor");
                });

            modelBuilder.Entity("EnergyCom.Domains.CalculoDados", b =>
                {
                    b.Navigation("Faturas");
                });

            modelBuilder.Entity("EnergyCom.Domains.Consumidor", b =>
                {
                    b.Navigation("Ucs");
                });

            modelBuilder.Entity("EnergyCom.Domains.Uc", b =>
                {
                    b.Navigation("CalculoDados");

                    b.Navigation("Faturas");
                });
#pragma warning restore 612, 618
        }
    }
}
